[program:api_consum]
command=/home/erpnext/api_consum_env/bin/uvicorn app.main:app --host 127.0.0.1 --port 8183
directory=/home/erpnext/.services/api_consum
user=erpnext
autostart=true
autorestart=true
stopsignal=TERM
stdout_logfile=/home/erpnext/.services/api_consum/logs/api_consum.log
stderr_logfile=/home/erpnext/.services/api_consum/logs/api_consum.err
environment=PYTHONUNBUFFERED=1
