"""Shared per-site equipment guardrail (hard requirement 2026-07-29).

A household must NEVER be told to act on heating/cooling equipment it
doesn't have (memory: feedback_per_site_equipment_profile). This module is
the SINGLE source of the forbidden-term lists and the text-matching logic,
consumed by two independent surfaces that both narrate equipment-adjacent
advice from the same `comfort_flex.equipment` profile
(`app.services.consumption.comfort_flex_for`):

- `app.services.ai.advice.AdviceSkill` — LLM-narrated forecast advice
  (dashboard card + S7 email), operating on a list of short advice TIPS.
- the AEMET weather-alert banner (`/consumption/environment`'s
  `weather_alert`) — a single static `energy_advisory_es/en` SENTENCE
  string sourced verbatim from api_exo, never generated by an LLM here.

Both paths must reach the SAME verdict for the SAME equipment profile —
hence one shared term list and one shared "does this text mention
equipment we don't have" primitive.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

# NOTE: matched against text with hyphens stripped (see `hits` below), so
# terms are written WITHOUT hyphens (e.g. "precal" catches "precalienta",
# "pre-calienta" AND "precalentar" once the hyphen is gone) and use the
# shortest root common to all Spanish conjugations, not a full word.
FORBIDDEN_TERMS: Dict[str, List[str]] = {
    "electric_heating": [
        "calefacción", "calefactor", "precal", "bomba de calor",
        "radiador", "caldera eléctrica", "termostato de calefacción",
        "heating", "preheat", "heat pump", "radiator", "furnace",
    ],
    "electric_cooling": [
        "aire acondicionado", "climatizador", "climatización", "preenfr",
        "a/c", "hvac", "ac",
        "air conditioning", "airconditioning", "precool",
    ],
}

# Bare tokens too short/generic for a plain substring check (e.g. "ac" would
# false-positive inside "reaction", "back", "vacío"...) — matched with word
# boundaries instead. Anything not listed here keeps the substring check.
_WORD_BOUNDARY_TERMS = {"ac"}
_WORD_RE_CACHE: Dict[str, "re.Pattern[str]"] = {}

# Equipment-neutral passive measures — safe to suggest to ANY household
# regardless of what it has installed, used to backfill whatever gets
# stripped so the banner/advice never ships silently empty.
_PASSIVE_TIP: Dict[str, Dict[str, str]] = {
    "electric_cooling": {
        "es": ("Cierra persianas y toldos durante el día para bloquear el sol, "
              "ventila por la noche cuando refresque, evita usar electrodomésticos "
              "que generen calor (horno, secadora) en las horas centrales, e "
              "hidrátate bien."),
        "en": ("Close shutters and awnings during the day to block the sun, "
              "ventilate at night once it cools down, avoid heat-generating "
              "appliances (oven, dryer) during peak midday hours, and stay well "
              "hydrated."),
    },
    "electric_heating": {
        "es": ("Aprovecha las horas de sol para calentar la vivienda de forma "
              "natural, refuerza el aislamiento de puertas y ventanas, y "
              "abrígate bien en las horas más frías."),
        "en": ("Make the most of sunlight hours to warm the home naturally, "
              "reinforce door/window insulation, and dress warmly during the "
              "coldest hours."),
    },
}

_FALLBACK_TIP: Dict[str, str] = {
    "es": "Adelanta lavadora/lavavajillas a las horas más baratas del día.",
    "en": "Shift deferrable appliances (washer, dishwasher) to the cheapest hours of the day.",
}


def missing_terms(equipment: Optional[Dict[str, Any]]) -> List[str]:
    """Combined forbidden-term list for whichever equipment categories the
    household does NOT have (no row / explicit false / unknown all resolve
    to `False` upstream in `comfort_flex_for` — conservative by design, so
    "unknown" is treated exactly like "confirmed absent")."""
    equipment = equipment or {}
    forbidden: List[str] = []
    if not equipment.get("electric_heating", False):
        forbidden += FORBIDDEN_TERMS["electric_heating"]
    if not equipment.get("electric_cooling", False):
        forbidden += FORBIDDEN_TERMS["electric_cooling"]
    return forbidden


def hits(text: str, forbidden: List[str]) -> bool:
    """Case-insensitive, hyphen-agnostic check against `forbidden`. Bare
    short tokens in `_WORD_BOUNDARY_TERMS` (e.g. "ac") match on WORD
    boundaries only — api_exo's EN heat advisory says "reduce AC load"
    (no slash, unlike the ES "carga del A/C") — plain substring would also
    false-positive inside unrelated words ("reaction", "back"...). Every
    other term keeps the simple substring check."""
    if not text or not forbidden:
        return False
    low = text.lower().replace("-", "")
    for term in forbidden:
        if term in _WORD_BOUNDARY_TERMS:
            pat = _WORD_RE_CACHE.get(term)
            if pat is None:
                pat = _WORD_RE_CACHE[term] = re.compile(r"\b" + re.escape(term) + r"\b")
            if pat.search(low):
                return True
        elif term in low:
            return True
    return False


def fallback_tip(lang: str) -> str:
    return _FALLBACK_TIP.get(lang, _FALLBACK_TIP["es"])


_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")


def _split_sentences(text: str) -> List[str]:
    return [p for p in _SENTENCE_SPLIT.split(text.strip()) if p]


def scrub_advisory_text(text: Optional[str], equipment: Optional[Dict[str, Any]],
                        lang: str = "es") -> Optional[str]:
    """Sentence-level scrub for a single free-text advisory string (the
    AEMET banner's `energy_advisory_es/en`, sourced verbatim from api_exo —
    never generated here). Drops any sentence mentioning heating/cooling
    equipment the household lacks and backfills with an equipment-neutral
    passive-measures sentence for whichever category triggered a removal,
    so the banner never ends up blank (spec: 'Do NOT leave it empty').

    A household WITH both electric_heating and electric_cooling passes the
    text through untouched. Equipment unknown (no comfort_flex row at all)
    resolves to all-false upstream in `comfort_flex_for`, so it's scrubbed
    exactly like a confirmed-absent household — conservative by design,
    never asserting equipment we can't confirm."""
    if not text:
        return text
    equipment = equipment or {}
    missing_cooling = not equipment.get("electric_cooling", False)
    missing_heating = not equipment.get("electric_heating", False)
    if not missing_cooling and not missing_heating:
        return text

    cooling_terms = FORBIDDEN_TERMS["electric_cooling"] if missing_cooling else []
    heating_terms = FORBIDDEN_TERMS["electric_heating"] if missing_heating else []

    kept: List[str] = []
    removed_cooling = False
    removed_heating = False
    for sentence in _split_sentences(text):
        hit_cooling = missing_cooling and hits(sentence, cooling_terms)
        hit_heating = missing_heating and hits(sentence, heating_terms)
        if hit_cooling or hit_heating:
            removed_cooling = removed_cooling or hit_cooling
            removed_heating = removed_heating or hit_heating
            continue
        kept.append(sentence)

    if not removed_cooling and not removed_heating:
        return text  # nothing in this particular text was equipment-specific

    if removed_cooling:
        kept.append(_PASSIVE_TIP["electric_cooling"].get(lang, _PASSIVE_TIP["electric_cooling"]["es"]))
    if removed_heating:
        kept.append(_PASSIVE_TIP["electric_heating"].get(lang, _PASSIVE_TIP["electric_heating"]["es"]))
    return " ".join(kept).strip()


def scrub_alerts(alerts: List[Dict[str, Any]], equipment: Optional[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Gate `energy_advisory_es`/`energy_advisory_en` on every alert in a
    `/weather/alerts` list. Used by `/consumption/environment` before the
    payload reaches the browser.

    Returns a NEW list of shallow-copied dicts — never mutates the input.
    `exo_client._get`'s in-process TTL cache returns the SAME parsed dict
    object to every caller within the cache window; two households sharing
    coordinates (same town) would otherwise poison each other's advisory
    text with the wrong household's equipment gating."""
    out: List[Dict[str, Any]] = []
    for a in alerts or []:
        a = dict(a)
        if a.get("energy_advisory_es"):
            a["energy_advisory_es"] = scrub_advisory_text(a["energy_advisory_es"], equipment, "es")
        if a.get("energy_advisory_en"):
            a["energy_advisory_en"] = scrub_advisory_text(a["energy_advisory_en"], equipment, "en")
        out.append(a)
    return out
